default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode 
  pool: 5
  user: postgres
  password: postgres
 
development:
  <<: *default
  database: anoncast_dev
 
test:
  <<: *default
  database: anoncast_test
 
production:
  <<: *default
  database: anoncast_prod
 
